//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2PNewsTicker.WinPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L2PNewsTicker.WinPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Announcement ähnelt.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ankündigung ähnelt.
        /// </summary>
        public static string AnnouncementDE {
            get {
                return ResourceManager.GetString("AnnouncementDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Announcements ähnelt.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ankündigungen ähnelt.
        /// </summary>
        public static string AnnouncementsDE {
            get {
                return ResourceManager.GetString("AnnouncementsDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assignment ähnelt.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übung ähnelt.
        /// </summary>
        public static string AssignmentDE {
            get {
                return ResourceManager.GetString("AssignmentDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assignments ähnelt.
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungen ähnelt.
        /// </summary>
        public static string AssignmentsDE {
            get {
                return ResourceManager.GetString("AssignmentsDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The RWTH Servers replied with a authorization problem. Please Authorize the App ähnelt.
        /// </summary>
        public static string AuthorizationProblem {
            get {
                return ResourceManager.GetString("AuthorizationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die RWTH Server haben ein Problem mit der Autorisierung gemeldet. Bitte erneut autorisieren. ähnelt.
        /// </summary>
        public static string AuthorizationProblemDE {
            get {
                return ResourceManager.GetString("AuthorizationProblemDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorize ähnelt.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autorisieren ähnelt.
        /// </summary>
        public static string AuthorizeDE {
            get {
                return ResourceManager.GetString("AuthorizeDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string CancelDE {
            get {
                return ResourceManager.GetString("CancelDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Progress is being Cancelled. This may take a moment to clean up network ähnelt.
        /// </summary>
        public static string CancelInfo {
            get {
                return ResourceManager.GetString("CancelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update wird abgebrochen. Dies kann einen Moment dauern um das Netzwerk wieder frei zu geben ähnelt.
        /// </summary>
        public static string CancelInfoDE {
            get {
                return ResourceManager.GetString("CancelInfoDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string ConfigDE {
            get {
                return ResourceManager.GetString("ConfigDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current And Last Semester ähnelt.
        /// </summary>
        public static string CurrentAndLastSemester {
            get {
                return ResourceManager.GetString("CurrentAndLastSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelles und letztes Semester ähnelt.
        /// </summary>
        public static string CurrentAndLastSemesterDE {
            get {
                return ResourceManager.GetString("CurrentAndLastSemesterDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Semester Only ähnelt.
        /// </summary>
        public static string CurrentSemesterOnly {
            get {
                return ResourceManager.GetString("CurrentSemesterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelles Semester ähnelt.
        /// </summary>
        public static string CurrentSemesterOnlyDE {
            get {
                return ResourceManager.GetString("CurrentSemesterOnlyDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tage ähnelt.
        /// </summary>
        public static string DaysDE {
            get {
                return ResourceManager.GetString("DaysDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discussion Item ähnelt.
        /// </summary>
        public static string DiscussionItem {
            get {
                return ResourceManager.GetString("DiscussionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diskussionsbeitrag ähnelt.
        /// </summary>
        public static string DiscussionItemDE {
            get {
                return ResourceManager.GetString("DiscussionItemDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discussions ähnelt.
        /// </summary>
        public static string Discussions {
            get {
                return ResourceManager.GetString("Discussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diskussionen ähnelt.
        /// </summary>
        public static string DiscussionsDE {
            get {
                return ResourceManager.GetString("DiscussionsDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fertig ähnelt.
        /// </summary>
        public static string DoneDE {
            get {
                return ResourceManager.GetString("DoneDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        public static string FileDE {
            get {
                return ResourceManager.GetString("FileDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder ähnelt.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner ähnelt.
        /// </summary>
        public static string FolderDE {
            get {
                return ResourceManager.GetString("FolderDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Course Data from ähnelt.
        /// </summary>
        public static string GetDataFrom {
            get {
                return ResourceManager.GetString("GetDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hole Kurs-Daten von ähnelt.
        /// </summary>
        public static string GetDataFromDE {
            get {
                return ResourceManager.GetString("GetDataFromDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got Courses ähnelt.
        /// </summary>
        public static string GotCourses {
            get {
                return ResourceManager.GetString("GotCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursliste abgeholt ähnelt.
        /// </summary>
        public static string GotCoursesDE {
            get {
                return ResourceManager.GetString("GotCoursesDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stunden ähnelt.
        /// </summary>
        public static string HoursDE {
            get {
                return ResourceManager.GetString("HoursDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learning Material ähnelt.
        /// </summary>
        public static string LearningMaterial {
            get {
                return ResourceManager.GetString("LearningMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lernmaterial ähnelt.
        /// </summary>
        public static string LearningMaterialDE {
            get {
                return ResourceManager.GetString("LearningMaterialDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learning Materials ähnelt.
        /// </summary>
        public static string LearningMaterials {
            get {
                return ResourceManager.GetString("LearningMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lernmaterialien ähnelt.
        /// </summary>
        public static string LearningMaterialsDE {
            get {
                return ResourceManager.GetString("LearningMaterialsDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Literature ähnelt.
        /// </summary>
        public static string Literature {
            get {
                return ResourceManager.GetString("Literature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Literatur ähnelt.
        /// </summary>
        public static string LiteratureDE {
            get {
                return ResourceManager.GetString("LiteratureDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media Elements ähnelt.
        /// </summary>
        public static string MediaLibraries {
            get {
                return ResourceManager.GetString("MediaLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medien ähnelt.
        /// </summary>
        public static string MediaLibrariesDE {
            get {
                return ResourceManager.GetString("MediaLibrariesDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media Library ähnelt.
        /// </summary>
        public static string MediaLibrary {
            get {
                return ResourceManager.GetString("MediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string MediaLibraryDE {
            get {
                return ResourceManager.GetString("MediaLibraryDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please use a timespan of at least 15 minutes ähnelt.
        /// </summary>
        public static string MinTime {
            get {
                return ResourceManager.GetString("MinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte mindestens eine Zeitspanne von 15 Minuten angeben ähnelt.
        /// </summary>
        public static string MinTimeDE {
            get {
                return ResourceManager.GetString("MinTimeDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minuten ähnelt.
        /// </summary>
        public static string MinutesDE {
            get {
                return ResourceManager.GetString("MinutesDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Courses found for User ähnelt.
        /// </summary>
        public static string NoCoursesError {
            get {
                return ResourceManager.GetString("NoCoursesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Kurse gefunden für User ähnelt.
        /// </summary>
        public static string NoCoursesErrorDE {
            get {
                return ResourceManager.GetString("NoCoursesErrorDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Data for this item ähnelt.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Daten vorhanden ähnelt.
        /// </summary>
        public static string NoDataDE {
            get {
                return ResourceManager.GetString("NoDataDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Internet Connection ähnelt.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Internetverbindung ähnelt.
        /// </summary>
        public static string NoInternetDE {
            get {
                return ResourceManager.GetString("NoInternetDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing New ähnelt.
        /// </summary>
        public static string NothingNew {
            get {
                return ResourceManager.GetString("NothingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nichts Neues ähnelt.
        /// </summary>
        public static string NothingNewDE {
            get {
                return ResourceManager.GetString("NothingNewDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereit ähnelt.
        /// </summary>
        public static string ReadyDE {
            get {
                return ResourceManager.GetString("ReadyDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string RefreshDE {
            get {
                return ResourceManager.GetString("RefreshDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Changes ähnelt.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string SaveChangesDE {
            get {
                return ResourceManager.GetString("SaveChangesDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes Saved ähnelt.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen gespeichert ähnelt.
        /// </summary>
        public static string SavedDE {
            get {
                return ResourceManager.GetString("SavedDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared Document ähnelt.
        /// </summary>
        public static string SharedDocument {
            get {
                return ResourceManager.GetString("SharedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gemeinsames Dokument ähnelt.
        /// </summary>
        public static string SharedDocumentDE {
            get {
                return ResourceManager.GetString("SharedDocumentDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared Documents ähnelt.
        /// </summary>
        public static string SharedDocuments {
            get {
                return ResourceManager.GetString("SharedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gemeinsame Dokumente ähnelt.
        /// </summary>
        public static string SharedDocumentsDE {
            get {
                return ResourceManager.GetString("SharedDocumentsDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting... ähnelt.
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte... ähnelt.
        /// </summary>
        public static string StartingDE {
            get {
                return ResourceManager.GetString("StartingDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Timespan to query for news in the course rooms ähnelt.
        /// </summary>
        public static string TimeSpanSince {
            get {
                return ResourceManager.GetString("TimeSpanSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zeitspanne, in der nach Neuigkeiten gesucht werden soll ähnelt.
        /// </summary>
        public static string TimeSpanSinceDE {
            get {
                return ResourceManager.GetString("TimeSpanSinceDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This App will now open a web page in your browser. Please authorize this App and come back. ähnelt.
        /// </summary>
        public static string UserAuthorizationInformation {
            get {
                return ResourceManager.GetString("UserAuthorizationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Webseite wird im Browser geöffnet. Bitte diese App authorisieren und zurück kommen. ähnelt.
        /// </summary>
        public static string UserAuthorizationInformationDE {
            get {
                return ResourceManager.GetString("UserAuthorizationInformationDE", resourceCulture);
            }
        }
    }
}
